### ISSUE TITLE
License? Is this code available under an opensource license? 

### ISSUE THREAD

**Issue by jan-janssen** [mjwen/kimpy#1]
I see that the general openkim code is available under COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0 does this also apply to kimpy? If that is the case can you include a license file in the repository?

**Comment by mjwen** [comment]
Hi @jan-janssen 

Thanks for making a conda recipe for kimpy!  Yes, I think we can license kimpy under CDDL-1.0 without any problem and I just added a license file.

 @ellio167, agreed?

**Comment by jan-janssen** [comment]
@mjwen thanks a lot. If you want to join me as a maintainer of the conda-forge recipe, just post a comment to the pull request. I am always happy when developers join in maintaining the recipe.

**Comment by ellio167** [comment]
Yes, this seems good to me.  Thanks!
