### ISSUE TITLE
kimpy 2.0.0 claims to be incompatible with KIM API 2.3.0

### ISSUE THREAD

**Issue by ClaireWaters** [mjwen/kimpy#13]
When attempting to build a new version of the KDP with the most recent version of the KIM API (2.3.0) the build failed with an exception relating to version incompatibility between kimpy and the KIM API:

```
================================================================================
    KIM-API version = "2.3.0" is detected, which is incompatible with the current
      kimpy version = "2.0.0".
   
    Try one of these options:
   
      (1) Update KIM-API.
          The current kimpy is compatible with KIM-API versions:
          ["2.2.1" - "2.2.1"] (inclusive).
      (2) Use the latest kimpy.
          If you are using the latest kimpy, which is not compatible with this
          KIM-API version "2.3.0" yet. Please contact
          Mingjian Wen ([wenxx151@umn.edu](mailto:wenxx151@umn.edu))  or
          raise an issue on github so we update the kimpy.
```

If kimpy 2.0.0 is compatible with KIM API 2.3.0 the compatibility table [Here](https://github.com/openkim/kimpy/blob/a5e0f3a6c5af2d4f1b7be11e3208c235ee589f98/api_compatibility.txt) should be updated.

Otherwise, the source of the incompatibility between kimpy 2.0.0 and KIM API 2.3.0 should be identified, and in the longer-term kimpy should be patched to ensure compatibility with the most recent version of the KIM API.

**Comment by mjwen** [comment]
resolved in #14
