### ISSUE TITLE
pybind11 and pytest shouldn't be in install_requires

### ISSUE THREAD

**Issue by yurivict** [mjwen/kimpy#15]
pybind11 is a build-only dependency, pytest is a test dependency.

**Comment by yafshar** [comment]
If I remember correctly, in the past, there was a `tests_require` which is deprecated. @mjwen we can use `extra-require` for test dependency, but I am not sure if this is the best approach. @yurivict, do you have any specific suggestions?

**Comment by yurivict** [comment]
IMO you should just remove pybind11 and pytest from install_requires and add them to extra-require under the key "test". That's what other python projects do.

**Comment by mjwen** [comment]
Following the latest `setuptools` guide, we can add a `project.toml` file to specify the need of `pybind11` at build time. And let `pytest` be a test dependency only as @yurivict suggested. The kliff repo is actually doing it in this way and we need to update kimpy similarily.

**Comment by mjwen** [comment]
Fixed in #17 and close it.
