### ISSUE TITLE
Accessing collections with kimpy

### ISSUE THREAD

**Issue by jan-janssen** [mjwen/kimpy#2]
I can list the collections with the kim command line utility but kimpy does not find the collections. 

Here is a mybinder environment for testing: 
https://mybinder.org/v2/gh/jan-janssen/openkim-example/master?filepath=kimpy-debug.ipynb

My kimpy code: 
```
import kimpy
for i in range(kimpy.collection.get_number_of_collections()):
    print(kimpy.collection.get_collection(i))
```

My command line code: 
```
kim-api-collections-management list
```

**Comment by jan-janssen** [comment]
At least `kimpy.sem_ver.get_sem_ver()` returns `2.1.3+GNU` so it seems to be primarily an issue with identifying the collection location.

**Comment by mjwen** [comment]
There are three modules related to collections management. You may want to use `kimpy.collection` and `kimpy.collections` together to get the info (e.g. collection directory, collection items ... ) you want. See [example_collections.py](https://github.com/openkim/kimpy/blob/master/examples/example_collections.py) for an example.

**Comment by jan-janssen** [comment]
Thanks a lot, it seems to be just an issue of my potential location.

**Comment by jan-janssen** [comment]
Now it fails when accessing the potentials, even though they are available:

https://mybinder.org/v2/gh/jan-janssen/openkim-example/master

```
extent, error = col.cache_list_of_item_metadata_files(
    kimpy.collection_item_type.simulatorModel,
    "Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu",
)
check_error(error, 'cache_list_of_item_metadata_files')

```

**Comment by mjwen** [comment]
This seems a problem from the kim-api. Can you provide more info, e.g. how you installed it (from source or via package manager), what version, what is the system...

@ellio167 Any ideas? I tried other simulator models and and portable models. All give similar errors. Below is an example of the error. These dots on line 2 seems suspicious.  

<img width="925" alt="Screen Shot 2019-11-03 at 5 26 14 PM" src="https://user-images.githubusercontent.com/10203513/68095523-163dae00-fe5f-11e9-89b7-557ddcf9cdec.png">

**Comment by ellio167** [comment]
This is likely something due to the way `conda` does the build and relocation of files.  It does look like if the `****`'s were removed from the string on line 2 it  would probably work ok.

**Comment by jan-janssen** [comment]
I build it using conda - my build script is https://github.com/conda-forge/kim-api-feedstock/blob/master/recipe/build.sh

**Comment by jan-janssen** [comment]
> This is likely something due to the way `conda` does the build and relocation of files. It does look like if the `****`'s were removed from the string on line 2 it would probably work ok.

That is correct the file is located at: 
`/srv/conda/envs/notebook/lib/openkim-models/simulator-models/Sim_LAMMPS_LJcut_AkersonElliott_Alchemy_PbAu/libkim-api-simulator-model.so`

In terms of the build process conda-forge is using patchelf to modify the path.

**Comment by ellio167** [comment]
The values for `KIM_API_SYSTEM_MODEL_DRIVERS_DIR` (and the corresponding values for MODELS and SIMULATOR_MODELS) set here
https://github.com/conda-forge/kim-api-feedstock/blob/b0db1a0b8ebe790f4d569d5274fc2c2cd715acb8/recipe/build.sh#L2

are being embedded  as strings in the `libkim-api.so` library.

It appears the patchelf process has correctly rewritten the value of the string, but has not managed to also update an associated length of the string.

Probably this  is occurring at this location
https://github.com/openkim/kim-api/blob/e76b6cc6632e7f0df6e266db2b0bdcf8d236d007/cpp/src/KIM_CollectionsImplementation.cpp#L481

I'm not sure exactly how this all works.  Maybe rewriting this routine to have a pointer  to the character array constants and then to separately construct the strings objects to be assigned to the map object would avoid the issue?

I don't know enough about conda to know how to setup a testing environment for this.

@jan-janssen can you try this out?  Or provide me with instructions/links for how to get this all set up on my end?

**Comment by jan-janssen** [comment]
I am a bit confused why you store the path as absolute path inside the library. Is not it possible to store the relative path? In terms of the conda build process, I am also just a user of conda, basically I checkout the recipe and call `conda build kim-api-feedstock/recipe` to build it.

**Comment by ellio167** [comment]
These directories can be placed anywhere on the system via the CMAKE options being used in the  configuration process.  So, there is no choice but to store the absolute path.  Regardless, conda is correctly updating the path strings in the library file but it seems that C++ has done some sort of optimization where it hard-codes the (original) length of the string in the library file.  I expect that this can be overcome by making some minor changes to the way we do things in the kim-api code.

Just to speed things up, can you point me to the conda recipe's for the kim-api and openkim-models packages?

**Comment by jan-janssen** [comment]
https://github.com/conda-forge/kim-api-feedstock 
and 
https://github.com/conda-forge/openkimmodels-feedstock

If you want to I can also add you as a maintainer.

**Comment by ellio167** [comment]
Sure, i’ll be happy to be a co-maintainer

Sent from my iPhone6s
https://z.umn.edu/relliott

**Comment by jan-janssen** [comment]
@ellio167 did you have any chance to look into this?

**Comment by ellio167** [comment]
Sorry not yet, but I'll try to look at it this morning.

Ryan

On Thu, 7 Nov 2019, Jan Janssen wrote:

> @ellio167 did you have any chance to look into this?
>
>

-- 
Ryan S. Elliott, Ph.D. and Professor
Aerospace Engineering & Mechanics, University of Minnesota
(612) 624-2376 (626-1558 fax)
https://z.umn.edu/relliott
download vCard <https://z.umn.edu/relliott_vcf>
----------
Hofstadter's Law: It always takes longer than you expect, even when you
    take into account Hofstadter's Law.

                                                Douglas R. Hofstadter, 1979
----------

**Comment by ellio167** [comment]
@jan-janssen OK, I've managed to set this  up on my mac.  I build the kim-api and kimpy packages locally and, interestingly, I am not able to reproduce the problem.

I guess, next, I'll try to do this all through a docker ubuntu container  to see if it occurs on linux.

**Comment by ellio167** [comment]
@jan-janssen OK, I've confirmed the originally reported behavior on a ubuntu docker container.
I've created a patch and updated the feedstock.

https://github.com/ellio167/kim-api-feedstock/tree/add-patch

Take a look at that and let me know what you think.

**Comment by jan-janssen** [comment]
@ellio167 I merged the changes and I am currently testing the updated version. But I am wondering what is the difference between the sources from GitHub and those from the amazon cloud? For conda-forge it is much easier to handle the patching of tar.gz sources, rather than tar.xz, that is why I would prefer to continue using the github repository.

**Comment by jan-janssen** [comment]
Perfect now everything is working fine.

**Comment by ellio167** [comment]
@jan-janssen The official tarballs are just that.  The official distribution of the kim-api release.  We specifically avoid  github archives because they are not guaranteed to have a stable checksum.

Preferably conda will support xz archive compression (as most other package managers do), which would then allow us to use the native patch support.  Until then, I would prefer to use the current setup we have for the kim-api conda package.
