### ISSUE TITLE
Calling kimpy function "create_paddings" failed

### ISSUE THREAD

**Issue by niloufareabi** [mjwen/kimpy#29]
**Hi,
I have problem running md calculation with kim calculator. this is my 2D structure:**

atoms= ase.build.mx2(formula='MoS2', kind='2H', a=3.1910 , thickness=3.1402, size=(6, 6, 1), vacuum=None)
atoms.calc = KIM("SW_MX2_WenShirodkarPlechac_2017_MoS__MO_201919462778_001")

**this is the error:**

KimpyError: Calling kimpy function "create_paddings" failed:
  In inverting the cell matrix, the determinant is 0!

**Is there anything I have to do for 2D materials? because the problem comes from the 3rd vector of the cell which is zero.**
Cell([[19.146, 0.0, 0.0], [-9.573, 16.58092238085686, 0.0], [0.0, 0.0, 0.0]])

**Comment by mjwen** [comment]
Hi @niloufareabi, 

The KIM calculator (and the underlying kimpy package) need non-zero cell vectors in all three directions to work. In your case with 2D materials, the cell vector `c` is actually zero as you showed. 

You can create an ASE atoms object to avoid this setting a non-zero `vacuum`, for example: 
```python
In [1]: atoms= ase.build.mx2(formula='MoS2', kind='2H', a=3.1910 , thickness=3.1402, size=(6, 6, 1), vacuum=100)
```

**Comment by niloufareabi** [comment]
Thank you @mjwen , it worked well. 
But I have a question, doesn't it affect anything? 
And another thing, can I change the vector 0 0 0  to a small number like 0.1 instead?

**Comment by mjwen** [comment]
It won't affect anything as long as your vacuum is larger than the cutoff distance of your potential model. For most potentials , the cutoff is less than 10 Angstrom, so a vacuum of 100 is safe. This means a value of 0.1 won't work.

**Comment by niloufareabi** [comment]
Ok then, thanks a lot :)
