### ISSUE TITLE
pickling

### ISSUE THREAD

**Issue by mjwen** [mjwen/kimpy#7]
Currently, kimpy objects are not pickable, which makes it difficult to use `multiprocessing`, especially in py3.8 and higher. It would be great to add pickle support. 

This can be achieved when creating the wrappings using pybind11, see https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

**Comment by ellio167** [comment]
Can you explain the need/use of this a bit more?  To make this work for Model objects etc, could be impossible.  I'm not sure there would be any way to pickle the various "buffers" that can be used since the kim-api has no idea about the size or data types that are contained there.

**Comment by mjwen** [comment]
Python 3.8 multiprocessing module switches the default start method to `spawn` from `fork` on macOS. With `spawn`, if I create a kim-api object and want to send it to a newly created process, this object needs to be picklable. 

All this comes from the fitting code I've been working on -- specifically, a user creates an instance of a model, then internally the fitting code distributed the model and a subset of the whole training set to the spawned process to compute the energies and forces... 

This is not a huge problem though, because we can specify the starting method back `mp.set_start_method("fork")`. If some part of the kim-api is not picklable, we will just have to use the fork start method.

**Comment by ellio167** [comment]
I’m pretty sure the kim-api model objects will not be picklable.

Perhaps instead of creating a model object and transferring it to the processes you could just use the model name to communicate between the processes and then create the model objects on each process.
